services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install && npm run build:css
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: YOUR_MAIL_URL
        sync: false
      - key: SITE_URL
        sync: false